<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Analog\\Analog' => $vendorDir . '/analog/analog/lib/Analog/Analog.php',
    'Analog\\Handler\\Amon' => $vendorDir . '/analog/analog/lib/Analog/Handler/Amon.php',
    'Analog\\Handler\\Apprise' => $vendorDir . '/analog/analog/lib/Analog/Handler/Apprise.php',
    'Analog\\Handler\\Buffer' => $vendorDir . '/analog/analog/lib/Analog/Handler/Buffer.php',
    'Analog\\Handler\\Buffer\\Destructor' => $vendorDir . '/analog/analog/lib/Analog/Handler/Buffer/Destructor.php',
    'Analog\\Handler\\ChromeLogger' => $vendorDir . '/analog/analog/lib/Analog/Handler/ChromeLogger.php',
    'Analog\\Handler\\EchoConsole' => $vendorDir . '/analog/analog/lib/Analog/Handler/EchoConsole.php',
    'Analog\\Handler\\File' => $vendorDir . '/analog/analog/lib/Analog/Handler/File.php',
    'Analog\\Handler\\FirePHP' => $vendorDir . '/analog/analog/lib/Analog/Handler/FirePHP.php',
    'Analog\\Handler\\GELF' => $vendorDir . '/analog/analog/lib/Analog/Handler/GELF.php',
    'Analog\\Handler\\IFTTT' => $vendorDir . '/analog/analog/lib/Analog/Handler/IFTTT.php',
    'Analog\\Handler\\Ignore' => $vendorDir . '/analog/analog/lib/Analog/Handler/Ignore.php',
    'Analog\\Handler\\LevelBuffer' => $vendorDir . '/analog/analog/lib/Analog/Handler/LevelBuffer.php',
    'Analog\\Handler\\LevelName' => $vendorDir . '/analog/analog/lib/Analog/Handler/LevelName.php',
    'Analog\\Handler\\Mail' => $vendorDir . '/analog/analog/lib/Analog/Handler/Mail.php',
    'Analog\\Handler\\Mongo' => $vendorDir . '/analog/analog/lib/Analog/Handler/Mongo.php',
    'Analog\\Handler\\Multi' => $vendorDir . '/analog/analog/lib/Analog/Handler/Multi.php',
    'Analog\\Handler\\Null' => $vendorDir . '/analog/analog/lib/Analog/Handler/Null.php',
    'Analog\\Handler\\PDO' => $vendorDir . '/analog/analog/lib/Analog/Handler/PDO.php',
    'Analog\\Handler\\Post' => $vendorDir . '/analog/analog/lib/Analog/Handler/Post.php',
    'Analog\\Handler\\Redis' => $vendorDir . '/analog/analog/lib/Analog/Handler/Redis.php',
    'Analog\\Handler\\Slackbot' => $vendorDir . '/analog/analog/lib/Analog/Handler/Slackbot.php',
    'Analog\\Handler\\Stderr' => $vendorDir . '/analog/analog/lib/Analog/Handler/Stderr.php',
    'Analog\\Handler\\Syslog' => $vendorDir . '/analog/analog/lib/Analog/Handler/Syslog.php',
    'Analog\\Handler\\Threshold' => $vendorDir . '/analog/analog/lib/Analog/Handler/Threshold.php',
    'Analog\\Handler\\Variable' => $vendorDir . '/analog/analog/lib/Analog/Handler/Variable.php',
    'Analog\\Handler\\WPMail' => $vendorDir . '/analog/analog/lib/Analog/Handler/WPMail.php',
    'Analog\\Logger' => $vendorDir . '/analog/analog/lib/Analog/Logger.php',
    'ChromePhp' => $vendorDir . '/analog/analog/lib/ChromePhp.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'Dealerdirect\\Composer\\Plugin\\Installers\\PHPCodeSniffer\\Plugin' => $vendorDir . '/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php',
    'Psr\\Log\\AbstractLogger' => $vendorDir . '/psr/log/src/AbstractLogger.php',
    'Psr\\Log\\InvalidArgumentException' => $vendorDir . '/psr/log/src/InvalidArgumentException.php',
    'Psr\\Log\\LogLevel' => $vendorDir . '/psr/log/src/LogLevel.php',
    'Psr\\Log\\LoggerAwareInterface' => $vendorDir . '/psr/log/src/LoggerAwareInterface.php',
    'Psr\\Log\\LoggerAwareTrait' => $vendorDir . '/psr/log/src/LoggerAwareTrait.php',
    'Psr\\Log\\LoggerInterface' => $vendorDir . '/psr/log/src/LoggerInterface.php',
    'Psr\\Log\\LoggerTrait' => $vendorDir . '/psr/log/src/LoggerTrait.php',
    'Psr\\Log\\NullLogger' => $vendorDir . '/psr/log/src/NullLogger.php',
);
